[[redirects]]
  from = "/:pattern"
  to = "/patterns/:pattern"
  status = 200

[build]
  command = "npx prisma migrate deploy && npx prisma generate && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"